---
language: generic
dist: xenial
sudo: enabled
branches:
  only:
  - master
  - development

matrix:
  include:
    - name: "Ubuntu 14.04 (trusty)"
      env:
        - DISTRO='ubuntu:14.04'
    - name: "Ubuntu 16.04 (xenial)"
      env:
        - DISTRO='ubuntu:16.04'
    - name: "Ubuntu 18.04 (bionic)"
      env:
        - DISTRO='ubuntu:18.04'
    - name: "Debian 8 (jessie)"
      env:
        - DISTRO='debian:8'
    - name: "Debian 9 (stretch)"
      env:
        - DISTRO='debian:9'
    - name: "Debian (buster)"
      env:
        - DISTRO='debian:buster'

before_install:
  - |
    docker run \
      --detach \
      --rm \
      --tty \
      --privileged \
      --network=host \
      --name kthresher_on_${DISTRO/:/_} \
      --mount type=bind,src="$(pwd)",dst=/kthresher \
      ${DISTRO}
  - |
    docker exec \
    kthresher_on_${DISTRO/:/_} \
      bash -c \
       'apt-get update; \
        apt-get install -yq --no-install-suggests --no-install-recommends \
         python \
         python3 \
         python-apt \
         python3-apt \
         python-pip \
         python3-pip \
         python-setuptools \
         python3-setuptools'
  - |
    docker exec \
      kthresher_on_${DISTRO/:/_} \
      bash -c 'pip install tox'

script:
  - >
    docker exec \
      kthresher_on_${DISTRO/:/_} \
      bash -c 'cd /kthresher/; tox'
...
