language: python
dist: xenial
branches:
  only:
  - master
  - development

env:
  global:
  - VIRTUALENV_SYSTEM_SITE_PACKAGES=false

matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 3.6
    env: TOXENV=py36
  - python: 3.7
    env: TOXENV=py37
  - python: 3.7
    env: TOXENV=pycodestyle

before_install:
  - pip install tox

script:
  - tox
